title: Victor Iwuala
logo: Frame2.png
description: I am a data analyst with about three years of experience. I am proficient in statistical analysis, data mining, and visualization techniques, which allow me to uncover valuable insights and identify trends. I am adept with statistical and data analytics tools such as Excel, SQL, and Power BI. 
#show_downloads: true
#google_analytics:
theme: jekyll-theme-minimal
