title: Victor Iwuala
logo: Frame2.png
description: I'm a data analyst with a passion for turning raw numbers into meaningful stories that drive smarter decisions. I enjoy using tools like Power BI, Excel, and SQL to uncover insights that matter. 
#show_downloads: true
#google_analytics:
theme: jekyll-theme-minimal
