title: Victor Iwuala
logo: Frame.png
description: I am a data analyst with about three years of experience, I excel in working with diverse data sources and transforming complex datasets into actionable insights that support informed decision-making. I am proficient in statistical analysis, data mining, and visualization techniques, which allow me to uncover valuable insights and identify trends. I am adept with statistical and data analytics tools such as Excel, SQL, and Power BI. 
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
